# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera_nombre', models.CharField(max_length=230)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia_nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='DocenteHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_numero', models.CharField(max_length=40)),
                ('resolucion_anio', models.CharField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], default=2017, max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('remunerado', models.CharField(choices=[('Asalariado', 'Asalariado'), ('Ad Honorem', 'Ad Honorem')], default='Asalariado', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Docente-Horas',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_nombre', models.CharField(max_length=100)),
                ('hs_semanales', models.IntegerField(null=True)),
                ('hs_total_materia', models.IntegerField(null=True)),
                ('anio_academico', models.IntegerField(choices=[(1, '1er Año'), (2, '2do Año'), (3, '3er Año'), (4, '4to Año'), (5, '5to Año')])),
            ],
            options={
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_nombre', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=11)),
                ('apellidos', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Mujer', max_length=20)),
                ('legajo_numero', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('antiguedad', models.IntegerField()),
                ('activo', models.CharField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1, max_length=20)),
            ],
            options={
                'ordering': ['apellidos'],
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='PersonaHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_numero', models.IntegerField()),
                ('resolucion_anio', models.CharField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], default=2017, max_length=10)),
                ('hs_catedras', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Dependencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Persona')),
            ],
            options={
                'verbose_name_plural': 'Persona-Horas',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nombre', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Carrera')),
            ],
            options={
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='TipoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_docente', models.CharField(max_length=50)),
                ('porcentaje_aplicado', models.IntegerField(null=True)),
                ('hs_institucionales', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Docente',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Periodo'),
        ),
        migrations.AddField(
            model_name='materia',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Plan'),
        ),
        migrations.AddField(
            model_name='docentehoras',
            name='docente_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.TipoDocente'),
        ),
        migrations.AddField(
            model_name='docentehoras',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Materia'),
        ),
        migrations.AddField(
            model_name='docentehoras',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Persona'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='sedes',
            field=models.ManyToManyField(to='horas.Sede'),
        ),
    ]
