# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docentehoras',
            old_name='personal',
            new_name='persona',
        ),
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='personahoras',
            name='resolucion_anio',
            field=models.CharField(choices=[('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default='2017', max_length=10),
        ),
    ]
