# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='docentehoras',
            options={'verbose_name_plural': 'Docente-Horas'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['id'], 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellido'], 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='personalhoras',
            options={'verbose_name_plural': 'Personal-Horas'},
        ),
        migrations.AlterModelOptions(
            name='personaltipo',
            options={'verbose_name_plural': 'Tipos de Personal'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name_plural': 'Sedes'},
        ),
        migrations.RemoveField(
            model_name='docentehoras',
            name='docente_tipo',
        ),
        migrations.DeleteModel(
            name='DocenteTipo',
        ),
    ]
