# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0002_auto_20170817_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentehoras',
            name='resolucion_anio',
            field=models.CharField(choices=[('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default='2017', max_length=10),
        ),
    ]
