# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0003_auto_20170817_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentehoras',
            name='hs_institucionales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docentehoras',
            name='porcentaje_aplicado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docentehoras',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horas.Sede'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=20),
        ),
    ]
