# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0004_auto_20170821_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(max_length=11, verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='personahoras',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha Fin'),
        ),
    ]
