# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0005_auto_20170822_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personahoras',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='personahoras',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='personahoras',
            name='hs_catedras',
            field=models.IntegerField(verbose_name='Horas cátedras'),
        ),
    ]
