# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0006_auto_20170822_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=40, verbose_name='Apellido/s'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(max_length=11, verbose_name='C.U.I.L.'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='legajo_numero',
            field=models.IntegerField(verbose_name='Legajo número'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=40, verbose_name='Nombre/s'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='personahoras',
            name='resolucion_anio',
            field=models.CharField(choices=[('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default='2017', max_length=10, verbose_name='Resolución año'),
        ),
        migrations.AlterField(
            model_name='personahoras',
            name='resolucion_numero',
            field=models.IntegerField(verbose_name='Resolución número'),
        ),
    ]
