# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0008_auto_20170822_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='carrera_nombre',
            field=models.CharField(max_length=230, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(max_length=11, unique=True, verbose_name='C.U.I.L.'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='legajo_numero',
            field=models.IntegerField(unique=True, verbose_name='Legajo número'),
        ),
    ]
