# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0009_auto_20170822_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_sistema', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='cambio',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.Version'),
        ),
    ]
