# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0010_auto_20170823_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_sistema',
            field=models.CharField(max_length=8),
        ),
    ]
