# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0011_auto_20170826_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='carrera_abreviada',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
