# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0012_carrera_carrera_abreviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
