# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0013_plan_plan_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='resolucion_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='resolucion_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
