# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0015_auto_20170830_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentehoras',
            name='remunerado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docentehoras',
            name='resolucion_anio',
            field=models.CharField(max_length=10, verbose_name='Resolución año'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='anio_academico',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(default='Sin Especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='personahoras',
            name='resolucion_anio',
            field=models.CharField(max_length=10, verbose_name='Resolución año'),
        ),
    ]
