# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0017_auto_20170904_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='dependencia_nombre',
            field=models.CharField(max_length=200),
        ),
    ]
