# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0018_auto_20170907_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(max_length=11, verbose_name='C.U.I.L.'),
        ),
    ]
