# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0022_auto_20180530_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='personahoras',
            name='remunerado',
            field=models.CharField(default=b'Remunerado', max_length=30),
        ),
    ]
